// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: dd6130ddf2edddfa9ce9370c7be21182a2e4f86a8df5e91516c2d3483c0b6496
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package amsterdam

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BlobCellsAndProofs to SSZ-encoded bytes.
func (t *BlobCellsAndProofs) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BlobCellsAndProofs to SSZ-encoded bytes, appending to the provided buffer.
func (t *BlobCellsAndProofs) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlobCellsAndProofs)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobCells'
	// Offset Field #1 'Proofs'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobCells'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobCells
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobCells")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			t := t[idx1]
			if t != nil {
				dst = append(dst, (*t)[:2048]...)
			}
		}
	}
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "Proofs")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			t := t[idx1]
			if t != nil {
				dst = append(dst, (*t)[:48]...)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BlobCellsAndProofs from SSZ-encoded bytes.
func (t *BlobCellsAndProofs) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	// Field #0 'BlobCells' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "BlobCells:o")
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Proofs:o")
	}
	{ // Field #0 'BlobCells' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.BlobCells
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlobCells")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "BlobCells")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "BlobCells")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "BlobCells[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if val2 == nil {
				val2 = new(BlobCell)
			}
			if len(buf) == 0 {
				val2 = nil
			} else {
				var val3 BlobCell
				copy(val3[:], buf)
				val2 = &val3
			}
			val1[idx1] = val2
		}
		t.BlobCells = val1
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:]
		val4 := t.Proofs
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Proofs")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Proofs")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "Proofs")
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Proofs[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val5 := val4[idx1]
			if val5 == nil {
				val5 = new(cancun.KZGProof)
			}
			if len(buf) == 0 {
				val5 = nil
			} else {
				var val6 cancun.KZGProof
				copy(val6[:], buf)
				val5 = &val6
			}
			val4[idx1] = val5
		}
		t.Proofs = val4
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BlobCellsAndProofs.
func (t *BlobCellsAndProofs) SizeSSZ() (size int) {
	if t == nil {
		t = new(BlobCellsAndProofs)
	}
	// Field #0 'BlobCells' offset (4 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'BlobCells'
		t := t.BlobCells
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			if t[i1] != nil {
				l1 := 2048
				size += l1
			}
		}
	}
	{ // Dynamic field #1 'Proofs'
		t := t.Proofs
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i2 := range vlen {
			if t[i2] != nil {
				l2 := 48
				size += l2
			}
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BlobCellsAndProofs.
func (t *BlobCellsAndProofs) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BlobCellsAndProofs using the given hash walker.
func (t *BlobCellsAndProofs) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlobCellsAndProofs)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobCells'
		t := t.BlobCells
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobCells")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			{
				idx := hh.StartTree(sszutils.TreeTypeBinary)
				vlen := uint64(0)
				if t != nil {
					hh.PutBytes((*t)[:2048])
					vlen = 1
				}
				hh.FillUpTo32()
				hh.MerkleizeWithMixin(idx, vlen, 1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			{
				idx := hh.StartTree(sszutils.TreeTypeBinary)
				vlen := uint64(0)
				if t != nil {
					hh.PutBytes((*t)[:48])
					vlen = 1
				}
				hh.FillUpTo32()
				hh.MerkleizeWithMixin(idx, vlen, 1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
