// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 820b4cafa9a1be86865103964e1d6252fd0736dba894b8bc3c88454bf01d34da
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package amsterdam

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetBlobsCellsRequest to SSZ-encoded bytes.
func (t *GetBlobsCellsRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetBlobsCellsRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetBlobsCellsRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetBlobsCellsRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'VersionedBlobHashes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'IndicesBitarray'
		dst = append(dst, t.IndicesBitarray[:16]...)
	}
	{ // Dynamic Field #0 'VersionedBlobHashes'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.VersionedBlobHashes
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "VersionedBlobHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetBlobsCellsRequest from SSZ-encoded bytes.
func (t *GetBlobsCellsRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 20 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 20)
	}
	// Field #0 'VersionedBlobHashes' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 20 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 20), "VersionedBlobHashes:o")
	}
	{ // Field #1 'IndicesBitarray' (static)
		buf := buf[4:20]
		copy(t.IndicesBitarray[:], buf)
	}
	{ // Field #0 'VersionedBlobHashes' (dynamic)
		buf := buf[offset0:]
		val1 := t.VersionedBlobHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "VersionedBlobHashes")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "VersionedBlobHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.VersionedBlobHashes = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetBlobsCellsRequest.
func (t *GetBlobsCellsRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetBlobsCellsRequest)
	}
	// Field #0 'VersionedBlobHashes' offset (4 bytes)
	// Field #1 'IndicesBitarray' static (16 bytes)
	size += 20
	{ // Dynamic field #0 'VersionedBlobHashes'
		size += len(t.VersionedBlobHashes) * 32
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetBlobsCellsRequest.
func (t *GetBlobsCellsRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetBlobsCellsRequest using the given hash walker.
func (t *GetBlobsCellsRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetBlobsCellsRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'VersionedBlobHashes'
		t := t.VersionedBlobHashes
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "VersionedBlobHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	{ // Field #1 'IndicesBitarray'
		hh.PutBytes(t.IndicesBitarray[:16])
	}
	hh.Merkleize(idx)
	return nil
}
