// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 733939cfca50fc1643f5895208a3ba7dbfd014796fb3aa6ec33e34dfd24b4448
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package prague

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetPayloadResponse to SSZ-encoded bytes.
func (t *GetPayloadResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetPayloadResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetPayloadResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	// Offset Field #4 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(cancun.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(cancun.BlobsBundle)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Dynamic Field #4 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+41:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > 256 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 256), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > 1073741824 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetPayloadResponse from SSZ-encoded bytes.
func (t *GetPayloadResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 45 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 45)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 45 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 45), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	// Field #4 'ExecutionRequests' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[41:45]))
	if offset4 < offset2 || offset4 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset2, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(cancun.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:offset4]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(cancun.BlobsBundle)
		}
		if err = t.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Field #4 'ExecutionRequests' (dynamic)
		buf := buf[offset4:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > 256 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 256), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), 1073741824), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetPayloadResponse.
func (t *GetPayloadResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	// Field #4 'ExecutionRequests' offset (4 bytes)
	size += 45
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #2 'BlobsBundle'
		size += t.BlobsBundle.SizeSSZ()
	}
	{ // Dynamic field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetPayloadResponse.
func (t *GetPayloadResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetPayloadResponse using the given hash walker.
func (t *GetPayloadResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(cancun.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(cancun.BlobsBundle)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	{ // Field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > 256 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 256), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1073741824, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(256, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
