// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 08bb3f5c94dc61c8f1185d8fdc4e635885811f84226e6cad8f594bda679b3d5f
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package prague

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *NewPayloadRequest to SSZ-encoded bytes.
func (t *NewPayloadRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *NewPayloadRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *NewPayloadRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'ExpectedBlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	// Offset Field #3 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(cancun.ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #1 'ExpectedBlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExpectedBlobVersionedHashes
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "ExpectedBlobVersionedHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	{ // Dynamic Field #3 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+40:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > 256 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 256), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > 1073741824 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *NewPayloadRequest from SSZ-encoded bytes.
func (t *NewPayloadRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 44)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 44 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 44), "ExecutionPayload:o")
	}
	// Field #1 'ExpectedBlobVersionedHashes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExpectedBlobVersionedHashes:o")
	}
	{ // Field #2 'ParentBeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	// Field #3 'ExecutionRequests' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[40:44]))
	if offset3 < offset1 || offset3 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset1, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(cancun.ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes' (dynamic)
		buf := buf[offset1:offset3]
		val1 := t.ExpectedBlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "ExpectedBlobVersionedHashes")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "ExpectedBlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.ExpectedBlobVersionedHashes = val1
	}
	{ // Field #3 'ExecutionRequests' (dynamic)
		buf := buf[offset3:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > 256 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 256), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), 1073741824), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *NewPayloadRequest.
func (t *NewPayloadRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'ExpectedBlobVersionedHashes' offset (4 bytes)
	// Field #2 'ParentBeaconBlockRoot' static (32 bytes)
	// Field #3 'ExecutionRequests' offset (4 bytes)
	size += 44
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #1 'ExpectedBlobVersionedHashes'
		size += len(t.ExpectedBlobVersionedHashes) * 32
	}
	{ // Dynamic field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *NewPayloadRequest.
func (t *NewPayloadRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *NewPayloadRequest using the given hash walker.
func (t *NewPayloadRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(cancun.ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes'
		t := t.ExpectedBlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "ExpectedBlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	{ // Field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > 256 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 256), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1073741824, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(256, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
