// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b2d2a1397783a305f6d39a25d4757a71c579c67167321e187dfc9954bdc4e61c
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package bogota

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[PayloadAttributes](`ssz-static:"false"`)

// MarshalSSZ marshals the *PayloadAttributes to SSZ-encoded bytes.
func (t *PayloadAttributes) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadAttributes to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadAttributes) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttributes)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	// Offset Field #3 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #4 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Static Field #5 'SlotNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.SlotNumber)
	}
	{ // Static Field #6 'TargetGasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.TargetGasLimit)
	}
	// Offset Field #7 'InclusionListTransactions'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #3 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+60:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #7 'InclusionListTransactions'
		binary.LittleEndian.PutUint32(dst[dstlen+112:], uint32(len(dst)-dstlen))
		t := t.InclusionListTransactions
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 8192), "InclusionListTransactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > 8192 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 8192), "InclusionListTransactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadAttributes from SSZ-encoded bytes.
func (t *PayloadAttributes) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 116 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 116)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	// Field #3 'Withdrawals' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[60:64]))
	if offset3 != 116 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 116), "Withdrawals:o")
	}
	{ // Field #4 'ParentBeaconBlockRoot' (static)
		buf := buf[64:96]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #5 'SlotNumber' (static)
		buf := buf[96:104]
		t.SlotNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'TargetGasLimit' (static)
		buf := buf[104:112]
		t.TargetGasLimit = binary.LittleEndian.Uint64(buf)
	}
	// Field #7 'InclusionListTransactions' (offset)
	offset7 := int(binary.LittleEndian.Uint32(buf[112:116]))
	if offset7 < offset3 || offset7 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset7, offset3, buflen), "InclusionListTransactions:o")
	}
	{ // Field #3 'Withdrawals' (dynamic)
		buf := buf[offset3:offset7]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	{ // Field #7 'InclusionListTransactions' (dynamic)
		buf := buf[offset7:]
		val2 := t.InclusionListTransactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "InclusionListTransactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "InclusionListTransactions")
		}
		if itemCount > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 8192), "InclusionListTransactions")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "InclusionListTransactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > 8192 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), 8192), "InclusionListTransactions[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.InclusionListTransactions = val2
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadAttributes.
func (t *PayloadAttributes) SizeSSZ() (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	// Field #3 'Withdrawals' offset (4 bytes)
	// Field #4 'ParentBeaconBlockRoot' static (32 bytes)
	// Field #5 'SlotNumber' static (8 bytes)
	// Field #6 'TargetGasLimit' static (8 bytes)
	// Field #7 'InclusionListTransactions' offset (4 bytes)
	size += 116
	{ // Dynamic field #3 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	{ // Dynamic field #7 'InclusionListTransactions'
		t := t.InclusionListTransactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadAttributes.
func (t *PayloadAttributes) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadAttributes using the given hash walker.
func (t *PayloadAttributes) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	{ // Field #3 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	{ // Field #4 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	{ // Field #5 'SlotNumber'
		hh.PutUint64(t.SlotNumber)
	}
	{ // Field #6 'TargetGasLimit'
		hh.PutUint64(t.TargetGasLimit)
	}
	{ // Field #7 'InclusionListTransactions'
		t := t.InclusionListTransactions
		vlen := uint64(len(t))
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 8192), "InclusionListTransactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > 8192 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 8192), "InclusionListTransactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(8192, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(8192, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
