// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d2da6e4c4c91f0b826cac904d03c8b748b5ad748fdcd0541e21d7b14eedaefe9
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package identification

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ClientVersion to SSZ-encoded bytes.
func (t *ClientVersion) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ClientVersion to SSZ-encoded bytes, appending to the provided buffer.
func (t *ClientVersion) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(ClientVersion)
	}
	dstlen := len(dst)
	// Offset Field #0 'Code'
	// Offset Field #1 'Name'
	// Offset Field #2 'Version'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #3 'Commit'
		dst = append(dst, t.Commit[:4]...)
	}
	{ // Dynamic Field #0 'Code'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		vlen := len(t.Code)
		if vlen > 2 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2), "Code")
		}
		dst = append(dst, t.Code[:]...)
	}
	{ // Dynamic Field #1 'Name'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		vlen := len(t.Name)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "Name")
		}
		dst = append(dst, t.Name[:]...)
	}
	{ // Dynamic Field #2 'Version'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		vlen := len(t.Version)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "Version")
		}
		dst = append(dst, t.Version[:]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ClientVersion from SSZ-encoded bytes.
func (t *ClientVersion) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 16 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 16)
	}
	// Field #0 'Code' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 16 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 16), "Code:o")
	}
	// Field #1 'Name' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Name:o")
	}
	// Field #2 'Version' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Version:o")
	}
	{ // Field #3 'Commit' (static)
		buf := buf[12:16]
		copy(t.Commit[:], buf)
	}
	{ // Field #0 'Code' (dynamic)
		buf := buf[offset0:offset1]
		if len(buf) > 2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 2), "Code")
		}
		t.Code = sszutils.ExpandSlice(t.Code, len(buf))
		copy(t.Code[:], buf)
	}
	{ // Field #1 'Name' (dynamic)
		buf := buf[offset1:offset2]
		if len(buf) > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 64), "Name")
		}
		t.Name = sszutils.ExpandSlice(t.Name, len(buf))
		copy(t.Name[:], buf)
	}
	{ // Field #2 'Version' (dynamic)
		buf := buf[offset2:]
		if len(buf) > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 64), "Version")
		}
		t.Version = sszutils.ExpandSlice(t.Version, len(buf))
		copy(t.Version[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ClientVersion.
func (t *ClientVersion) SizeSSZ() (size int) {
	if t == nil {
		t = new(ClientVersion)
	}
	// Field #0 'Code' offset (4 bytes)
	// Field #1 'Name' offset (4 bytes)
	// Field #2 'Version' offset (4 bytes)
	// Field #3 'Commit' static (4 bytes)
	size += 16
	{ // Dynamic field #0 'Code'
		size += len(t.Code)
	}
	{ // Dynamic field #1 'Name'
		size += len(t.Name)
	}
	{ // Dynamic field #2 'Version'
		size += len(t.Version)
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ClientVersion.
func (t *ClientVersion) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ClientVersion using the given hash walker.
func (t *ClientVersion) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ClientVersion)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Code'
		vlen := uint64(len(t.Code))
		if vlen > 2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2), "Code")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.Code[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2, vlen, 1))
	}
	{ // Field #1 'Name'
		vlen := uint64(len(t.Name))
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "Name")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.Name[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 1))
	}
	{ // Field #2 'Version'
		vlen := uint64(len(t.Version))
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 64), "Version")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.Version[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(64, vlen, 1))
	}
	{ // Field #3 'Commit'
		hh.PutBytes(t.Commit[:4])
	}
	hh.Merkleize(idx)
	return nil
}
