// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 20bab7c303a37abc20ab49b9c2e8707d61dbaa8dcc4434c01b040ce7c5f86256
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[ForkchoiceUpdatedResponse](`ssz-static:"false"`)

// MarshalSSZ marshals the *ForkchoiceUpdatedResponse to SSZ-encoded bytes.
func (t *ForkchoiceUpdatedResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ForkchoiceUpdatedResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *ForkchoiceUpdatedResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'PayloadStatus'
	// Offset Field #1 'PayloadID'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'PayloadStatus'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := &t.PayloadStatus
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "PayloadStatus")
		}
	}
	{ // Dynamic Field #1 'PayloadID'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.PayloadID
		if t != nil {
			dst = append(dst, (*t)[:8]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ForkchoiceUpdatedResponse from SSZ-encoded bytes.
func (t *ForkchoiceUpdatedResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	// Field #0 'PayloadStatus' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "PayloadStatus:o")
	}
	// Field #1 'PayloadID' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "PayloadID:o")
	}
	{ // Field #0 'PayloadStatus' (dynamic)
		buf := buf[offset0:offset1]
		if err = t.PayloadStatus.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "PayloadStatus")
		}
	}
	{ // Field #1 'PayloadID' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadID
		if len(buf) == 0 {
			val1 = nil
		} else {
			var val2 PayloadID
			copy(val2[:], buf)
			val1 = &val2
		}
		t.PayloadID = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ForkchoiceUpdatedResponse.
func (t *ForkchoiceUpdatedResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedResponse)
	}
	// Field #0 'PayloadStatus' offset (4 bytes)
	// Field #1 'PayloadID' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'PayloadStatus'
		size += t.PayloadStatus.SizeSSZ()
	}
	{ // Dynamic field #1 'PayloadID'
		if t.PayloadID != nil {
			l1 := 8
			size += l1
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ForkchoiceUpdatedResponse.
func (t *ForkchoiceUpdatedResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ForkchoiceUpdatedResponse using the given hash walker.
func (t *ForkchoiceUpdatedResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'PayloadStatus'
		t := &t.PayloadStatus
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "PayloadStatus")
		}
	}
	{ // Field #1 'PayloadID'
		t := t.PayloadID
		{
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			vlen := uint64(0)
			if t != nil {
				hh.PutBytes((*t)[:8])
				vlen = 1
			}
			hh.FillUpTo32()
			hh.MerkleizeWithMixin(idx, vlen, 1)
		}
	}
	hh.Merkleize(idx)
	return nil
}
