// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b4fb204be6d55dbee77e3eacfb8b2dd170bbd03632ce47af17b72e12f67ba9eb
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ForkchoiceState to SSZ-encoded bytes.
func (t *ForkchoiceState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ForkchoiceState to SSZ-encoded bytes, appending to the provided buffer.
func (t *ForkchoiceState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceState)
	}
	{ // Static Field #0 'HeadBlockHash'
		dst = append(dst, t.HeadBlockHash[:32]...)
	}
	{ // Static Field #1 'SafeBlockHash'
		dst = append(dst, t.SafeBlockHash[:32]...)
	}
	{ // Static Field #2 'FinalizedBlockHash'
		dst = append(dst, t.FinalizedBlockHash[:32]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ForkchoiceState from SSZ-encoded bytes.
func (t *ForkchoiceState) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 96 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 96)
	}
	{ // Field #0 'HeadBlockHash' (static)
		buf := buf[0:32]
		copy(t.HeadBlockHash[:], buf)
	}
	{ // Field #1 'SafeBlockHash' (static)
		buf := buf[32:64]
		copy(t.SafeBlockHash[:], buf)
	}
	{ // Field #2 'FinalizedBlockHash' (static)
		buf := buf[64:96]
		copy(t.FinalizedBlockHash[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ForkchoiceState.
func (t *ForkchoiceState) SizeSSZ() (size int) {
	return 96
}

// HashTreeRoot computes the SSZ hash tree root of the *ForkchoiceState.
func (t *ForkchoiceState) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ForkchoiceState using the given hash walker.
func (t *ForkchoiceState) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceState)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'HeadBlockHash'
		hh.PutBytes(t.HeadBlockHash[:32])
	}
	{ // Field #1 'SafeBlockHash'
		hh.PutBytes(t.SafeBlockHash[:32])
	}
	{ // Field #2 'FinalizedBlockHash'
		hh.PutBytes(t.FinalizedBlockHash[:32])
	}
	hh.Merkleize(idx)
	return nil
}
