// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 186bbbf4e139088ee5e38ef4aed9330f9bd771c3dda1f6533e7cc9d173343b19
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ForkchoiceUpdatedRequest to SSZ-encoded bytes.
func (t *ForkchoiceUpdatedRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ForkchoiceUpdatedRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *ForkchoiceUpdatedRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if t != nil {
			if dst, err = (*t).MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPath(err, "PayloadAttributes[0]")
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ForkchoiceUpdatedRequest from SSZ-encoded bytes.
func (t *ForkchoiceUpdatedRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if len(buf) == 0 {
			val1 = nil
		} else {
			var val2 PayloadAttributes
			if err = val2.UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPath(err, "PayloadAttributes[0]")
			}
			val1 = &val2
		}
		t.PayloadAttributes = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ForkchoiceUpdatedRequest.
func (t *ForkchoiceUpdatedRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if t.PayloadAttributes != nil {
			size += (*t.PayloadAttributes).SizeSSZ()
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ForkchoiceUpdatedRequest.
func (t *ForkchoiceUpdatedRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ForkchoiceUpdatedRequest using the given hash walker.
func (t *ForkchoiceUpdatedRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		{
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			vlen := uint64(0)
			if t != nil {
				if err := (*t).HashTreeRootWith(hh); err != nil {
					return sszutils.ErrorWithPath(err, "PayloadAttributes[0]")
				}
				vlen = 1
			}
			hh.FillUpTo32()
			hh.MerkleizeWithMixin(idx, vlen, 1)
		}
	}
	hh.Merkleize(idx)
	return nil
}
