// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 21488207b9da804719341e149c09c4f914375f4a1b74b5a29674b987367b1d48
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *NewPayloadRequest to SSZ-encoded bytes.
func (t *NewPayloadRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *NewPayloadRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *NewPayloadRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *NewPayloadRequest from SSZ-encoded bytes.
func (t *NewPayloadRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "ExecutionPayload:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *NewPayloadRequest.
func (t *NewPayloadRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *NewPayloadRequest.
func (t *NewPayloadRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *NewPayloadRequest using the given hash walker.
func (t *NewPayloadRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	hh.Merkleize(idx)
	return nil
}
