// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9cf437bad6082033104a61442a656a7334ecbd755d34380fbe7f0e4fd4c74c56
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *PayloadAttributes to SSZ-encoded bytes.
func (t *PayloadAttributes) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadAttributes to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadAttributes) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttributes)
	}
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadAttributes from SSZ-encoded bytes.
func (t *PayloadAttributes) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 60 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 60)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadAttributes.
func (t *PayloadAttributes) SizeSSZ() (size int) {
	return 60
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadAttributes.
func (t *PayloadAttributes) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadAttributes using the given hash walker.
func (t *PayloadAttributes) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	hh.Merkleize(idx)
	return nil
}
