// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: f7850a71cd0ebc243de6ae7bb1c0c119a0779382b145db38257415c0b99197c2
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package paris

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[PayloadStatus](`ssz-static:"false"`)

// MarshalSSZ marshals the *PayloadStatus to SSZ-encoded bytes.
func (t *PayloadStatus) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadStatus to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadStatus) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadStatus)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Status'
		dst = append(dst, byte(t.Status))
	}
	// Offset Field #1 'LatestValidHash'
	// Offset Field #2 'ValidationError'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #1 'LatestValidHash'
		binary.LittleEndian.PutUint32(dst[dstlen+1:], uint32(len(dst)-dstlen))
		t := t.LatestValidHash
		if t != nil {
			dst = append(dst, (*t)[:32]...)
		}
	}
	{ // Dynamic Field #2 'ValidationError'
		binary.LittleEndian.PutUint32(dst[dstlen+5:], uint32(len(dst)-dstlen))
		vlen := len(t.ValidationError)
		if vlen > 1024 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1024), "ValidationError")
		}
		dst = append(dst, t.ValidationError[:]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadStatus from SSZ-encoded bytes.
func (t *PayloadStatus) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 9 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 9)
	}
	{ // Field #0 'Status' (static)
		buf := buf[0:1]
		t.Status = PayloadValidationStatus(buf[0])
	}
	// Field #1 'LatestValidHash' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[1:5]))
	if offset1 != 9 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 9), "LatestValidHash:o")
	}
	// Field #2 'ValidationError' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[5:9]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "ValidationError:o")
	}
	{ // Field #1 'LatestValidHash' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.LatestValidHash
		if len(buf) == 0 {
			val1 = nil
		} else {
			var val2 Hash32
			copy(val2[:], buf)
			val1 = &val2
		}
		t.LatestValidHash = val1
	}
	{ // Field #2 'ValidationError' (dynamic)
		buf := buf[offset2:]
		if len(buf) > 1024 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), 1024), "ValidationError")
		}
		t.ValidationError = sszutils.ExpandSlice(t.ValidationError, len(buf))
		copy(t.ValidationError[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadStatus.
func (t *PayloadStatus) SizeSSZ() (size int) {
	if t == nil {
		t = new(PayloadStatus)
	}
	// Field #0 'Status' static (1 bytes)
	// Field #1 'LatestValidHash' offset (4 bytes)
	// Field #2 'ValidationError' offset (4 bytes)
	size += 9
	{ // Dynamic field #1 'LatestValidHash'
		if t.LatestValidHash != nil {
			l1 := 32
			size += l1
		}
	}
	{ // Dynamic field #2 'ValidationError'
		size += len(t.ValidationError)
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadStatus.
func (t *PayloadStatus) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadStatus using the given hash walker.
func (t *PayloadStatus) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadStatus)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Status'
		hh.PutUint8(uint8(t.Status))
	}
	{ // Field #1 'LatestValidHash'
		t := t.LatestValidHash
		{
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			vlen := uint64(0)
			if t != nil {
				hh.PutBytes((*t)[:32])
				vlen = 1
			}
			hh.FillUpTo32()
			hh.MerkleizeWithMixin(idx, vlen, 1)
		}
	}
	{ // Field #2 'ValidationError'
		vlen := uint64(len(t.ValidationError))
		if vlen > 1024 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1024), "ValidationError")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		hh.AppendBytes32(t.ValidationError[:])
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1024, vlen, 1))
	}
	hh.Merkleize(idx)
	return nil
}
