// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ac2e296dfe6857f48dc24f5376f2d117df6958ad200aca9b599c2353afd0f287
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package shanghai

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *ExecutionPayloadBody to SSZ-encoded bytes.
func (t *ExecutionPayloadBody) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *ExecutionPayloadBody to SSZ-encoded bytes, appending to the provided buffer.
func (t *ExecutionPayloadBody) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	dstlen := len(dst)
	// Offset Field #0 'Transactions'
	// Offset Field #1 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > 1048576 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1048576), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > 1073741824 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #1 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *ExecutionPayloadBody from SSZ-encoded bytes.
func (t *ExecutionPayloadBody) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	// Field #0 'Transactions' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "Transactions:o")
	}
	// Field #1 'Withdrawals' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Withdrawals:o")
	}
	{ // Field #0 'Transactions' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > 1048576 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1048576), "Transactions")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if len(buf) > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), 1073741824), "Transactions[%d]", idx1)
			}
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	{ // Field #1 'Withdrawals' (dynamic)
		buf := buf[offset1:]
		val3 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16), "Withdrawals")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val3
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *ExecutionPayloadBody.
func (t *ExecutionPayloadBody) SizeSSZ() (size int) {
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	// Field #0 'Transactions' offset (4 bytes)
	// Field #1 'Withdrawals' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #1 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *ExecutionPayloadBody.
func (t *ExecutionPayloadBody) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *ExecutionPayloadBody using the given hash walker.
func (t *ExecutionPayloadBody) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > 1048576 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1048576), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > 1073741824 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, 1073741824), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1073741824, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1048576, vlen, 32))
	}
	{ // Field #1 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
