// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d12543ab7f773f26f509d326a7c85c2e2c0771448aba168e9a90962dba802747
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package shanghai

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetPayloadBodiesByHashRequest to SSZ-encoded bytes.
func (t *GetPayloadBodiesByHashRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetPayloadBodiesByHashRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetPayloadBodiesByHashRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadBodiesByHashRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlockHashes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlockHashes'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlockHashes
		vlen := len(t)
		if vlen > 32 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "BlockHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetPayloadBodiesByHashRequest from SSZ-encoded bytes.
func (t *GetPayloadBodiesByHashRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlockHashes' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlockHashes:o")
	}
	{ // Field #0 'BlockHashes' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlockHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "BlockHashes")
		}
		if itemCount > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 32), "BlockHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.BlockHashes = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetPayloadBodiesByHashRequest.
func (t *GetPayloadBodiesByHashRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetPayloadBodiesByHashRequest)
	}
	// Field #0 'BlockHashes' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlockHashes'
		size += len(t.BlockHashes) * 32
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetPayloadBodiesByHashRequest.
func (t *GetPayloadBodiesByHashRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetPayloadBodiesByHashRequest using the given hash walker.
func (t *GetPayloadBodiesByHashRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadBodiesByHashRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlockHashes'
		t := t.BlockHashes
		vlen := uint64(len(t))
		if vlen > 32 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 32), "BlockHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(32, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
