// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9e11f66d103011a98f4afe06f3acd28213704d8c58d737dc740324ef847ee186
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package shanghai

import (
	"encoding/binary"

	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[GetPayloadResponse](`ssz-static:"false"`)

// MarshalSSZ marshals the *GetPayloadResponse to SSZ-encoded bytes.
func (t *GetPayloadResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetPayloadResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetPayloadResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetPayloadResponse from SSZ-encoded bytes.
func (t *GetPayloadResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 36 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 36)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 36 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 36), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetPayloadResponse.
func (t *GetPayloadResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	size += 36
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetPayloadResponse.
func (t *GetPayloadResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetPayloadResponse using the given hash walker.
func (t *GetPayloadResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	hh.Merkleize(idx)
	return nil
}
