// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 0e5a810963c5a8380da10617839570b7c9eb2ccc28db6f99a4a1b34e18b3792f
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package shanghai

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[GetPayloadBodiesByRangeRequest](`ssz-static:"true"`)

// MarshalSSZ marshals the *GetPayloadBodiesByRangeRequest to SSZ-encoded bytes.
func (t *GetPayloadBodiesByRangeRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetPayloadBodiesByRangeRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetPayloadBodiesByRangeRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadBodiesByRangeRequest)
	}
	{ // Static Field #0 'Start'
		dst = binary.LittleEndian.AppendUint64(dst, t.Start)
	}
	{ // Static Field #1 'Count'
		dst = binary.LittleEndian.AppendUint64(dst, t.Count)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetPayloadBodiesByRangeRequest from SSZ-encoded bytes.
func (t *GetPayloadBodiesByRangeRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 16 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 16)
	}
	if buflen > 16 {
		return sszutils.ErrTrailingDataFn(buflen - 16)
	}
	{ // Field #0 'Start' (static)
		buf := buf[0:8]
		t.Start = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'Count' (static)
		buf := buf[8:16]
		t.Count = binary.LittleEndian.Uint64(buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetPayloadBodiesByRangeRequest.
func (t *GetPayloadBodiesByRangeRequest) SizeSSZ() (size int) {
	return 16
}

// HashTreeRoot computes the SSZ hash tree root of the *GetPayloadBodiesByRangeRequest.
func (t *GetPayloadBodiesByRangeRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetPayloadBodiesByRangeRequest using the given hash walker.
func (t *GetPayloadBodiesByRangeRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadBodiesByRangeRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Start'
		hh.PutUint64(t.Start)
	}
	{ // Field #1 'Count'
		hh.PutUint64(t.Count)
	}
	hh.Merkleize(idx)
	return nil
}
