// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5a25d6fd1a63ecdfce4462366ada5726ef1606cff174e93cefe1c5a61b9f20a4
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package shanghai

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *PayloadAttributes to SSZ-encoded bytes.
func (t *PayloadAttributes) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *PayloadAttributes to SSZ-encoded bytes, appending to the provided buffer.
func (t *PayloadAttributes) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttributes)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	// Offset Field #3 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #3 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+60:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > 16 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *PayloadAttributes from SSZ-encoded bytes.
func (t *PayloadAttributes) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 64 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 64)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	// Field #3 'Withdrawals' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[60:64]))
	if offset3 != 64 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 64), "Withdrawals:o")
	}
	{ // Field #3 'Withdrawals' (dynamic)
		buf := buf[offset3:]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *PayloadAttributes.
func (t *PayloadAttributes) SizeSSZ() (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	// Field #3 'Withdrawals' offset (4 bytes)
	size += 64
	{ // Dynamic field #3 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *PayloadAttributes.
func (t *PayloadAttributes) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *PayloadAttributes using the given hash walker.
func (t *PayloadAttributes) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	{ // Field #3 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > 16 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
