// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 722197aa1dfe7e4292bee95aa7cbe1b7d038f0d8283e45389e991b2f4c1a80f9
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package osaka

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BlobAndProof](`ssz-static:"false"`)

// MarshalSSZ marshals the *BlobAndProof to SSZ-encoded bytes.
func (t *BlobAndProof) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BlobAndProof to SSZ-encoded bytes, appending to the provided buffer.
func (t *BlobAndProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlobAndProof)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Blob'
		dst = append(dst, t.Blob[:131072]...)
	}
	// Offset Field #1 'Proofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+131072:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "Proofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BlobAndProof from SSZ-encoded bytes.
func (t *BlobAndProof) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 131076 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 131076)
	}
	{ // Field #0 'Blob' (static)
		buf := buf[0:131072]
		copy(t.Blob[:], buf)
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[131072:131076]))
	if offset1 != 131076 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 131076), "Proofs:o")
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:]
		val1 := t.Proofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Proofs")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "Proofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.Proofs = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BlobAndProof.
func (t *BlobAndProof) SizeSSZ() (size int) {
	if t == nil {
		t = new(BlobAndProof)
	}
	// Field #0 'Blob' static (131072 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	size += 131076
	{ // Dynamic field #1 'Proofs'
		size += len(t.Proofs) * 48
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BlobAndProof.
func (t *BlobAndProof) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BlobAndProof using the given hash walker.
func (t *BlobAndProof) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlobAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Blob'
		hh.PutBytes(t.Blob[:131072])
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
