// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: a596da6cd7f5f8c2239017f4671e3cb074d510887bf49c8816013c61fe06f7dc
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package osaka

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetBlobsPartialResponse to SSZ-encoded bytes.
func (t *GetBlobsPartialResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetBlobsPartialResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetBlobsPartialResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetBlobsPartialResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobsAndProofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobsAndProofs'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobsAndProofs
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			t := t[idx1]
			if t != nil {
				dst = binary.LittleEndian.AppendUint32(dst, 4)
				if dst, err = (*t).MarshalSSZTo(dst); err != nil {
					return nil, sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d][0]", idx1)
				}
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetBlobsPartialResponse from SSZ-encoded bytes.
func (t *GetBlobsPartialResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobsAndProofs' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobsAndProofs:o")
	}
	{ // Field #0 'BlobsAndProofs' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobsAndProofs
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlobsAndProofs")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "BlobsAndProofs")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "BlobsAndProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "BlobsAndProofs[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if val2 == nil {
				val2 = new(BlobAndProof)
			}
			if len(buf) == 0 {
				val2 = nil
			} else {
				if len(buf) < 4 {
					return sszutils.ErrorWithPathf(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlobsAndProofs[%d]", idx1)
				}
				firstOffset := binary.LittleEndian.Uint32(buf[:4])
				if firstOffset != 4 {
					return sszutils.ErrorWithPathf(sszutils.ErrFirstOffsetMismatchFn(firstOffset, uint32(4)), "BlobsAndProofs[%d]", idx1)
				}
				buf := buf[4:]
				var val3 BlobAndProof
				if err = val3.UnmarshalSSZ(buf); err != nil {
					return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d][0]", idx1)
				}
				val2 = &val3
			}
			val1[idx1] = val2
		}
		t.BlobsAndProofs = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetBlobsPartialResponse.
func (t *GetBlobsPartialResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetBlobsPartialResponse)
	}
	// Field #0 'BlobsAndProofs' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			if t[i1] != nil {
				size += 4 // optional-list offset header
				size += (*t[i1]).SizeSSZ()
			}
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetBlobsPartialResponse.
func (t *GetBlobsPartialResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetBlobsPartialResponse using the given hash walker.
func (t *GetBlobsPartialResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetBlobsPartialResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			{
				idx := hh.StartTree(sszutils.TreeTypeBinary)
				vlen := uint64(0)
				if t != nil {
					if err := (*t).HashTreeRootWith(hh); err != nil {
						return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d][0]", idx1)
					}
					vlen = 1
				}
				hh.FillUpTo32()
				hh.MerkleizeWithMixin(idx, vlen, 1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
