// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: e573c9e976852db64d70e0dd88f25cef3ace3c954466db42fa4663d5e678c8ad
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package osaka

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[GetBlobsPartialRequest](`ssz-static:"false"`)

// MarshalSSZ marshals the *GetBlobsPartialRequest to SSZ-encoded bytes.
func (t *GetBlobsPartialRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetBlobsPartialRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetBlobsPartialRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetBlobsPartialRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobVersionedHashes
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobVersionedHashes")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetBlobsPartialRequest from SSZ-encoded bytes.
func (t *GetBlobsPartialRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobVersionedHashes' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobVersionedHashes:o")
	}
	{ // Field #0 'BlobVersionedHashes' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "BlobVersionedHashes")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "BlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.BlobVersionedHashes = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetBlobsPartialRequest.
func (t *GetBlobsPartialRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetBlobsPartialRequest)
	}
	// Field #0 'BlobVersionedHashes' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobVersionedHashes'
		size += len(t.BlobVersionedHashes) * 32
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetBlobsPartialRequest.
func (t *GetBlobsPartialRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetBlobsPartialRequest using the given hash walker.
func (t *GetBlobsPartialRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetBlobsPartialRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobVersionedHashes'
		t := t.BlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
