// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 405215a5ed0e898da30f4cab88e5094b922605ba9bce07253abd78638d6926f7
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package osaka

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[GetBlobsResponse](`ssz-static:"false"`)

// MarshalSSZ marshals the *GetBlobsResponse to SSZ-encoded bytes.
func (t *GetBlobsResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetBlobsResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetBlobsResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetBlobsResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobsAndProofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobsAndProofs'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobsAndProofs
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetBlobsResponse from SSZ-encoded bytes.
func (t *GetBlobsResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobsAndProofs' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobsAndProofs:o")
	}
	{ // Field #0 'BlobsAndProofs' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobsAndProofs
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlobsAndProofs")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "BlobsAndProofs")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "BlobsAndProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "BlobsAndProofs[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if val2 == nil {
				val2 = new(BlobAndProof)
			}
			if err = val2.UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
			val1[idx1] = val2
		}
		t.BlobsAndProofs = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetBlobsResponse.
func (t *GetBlobsResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	// Field #0 'BlobsAndProofs' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += t[i1].SizeSSZ()
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetBlobsResponse.
func (t *GetBlobsResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetBlobsResponse using the given hash walker.
func (t *GetBlobsResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
