// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8efb640aae9c11cae6f2aef928a75cd1afae2a3297f6a11bcdeb695305960538
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package cancun

import (
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BlobAndProof](`ssz-static:"true"`)

// MarshalSSZ marshals the *BlobAndProof to SSZ-encoded bytes.
func (t *BlobAndProof) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BlobAndProof to SSZ-encoded bytes, appending to the provided buffer.
func (t *BlobAndProof) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlobAndProof)
	}
	{ // Static Field #0 'Blob'
		dst = append(dst, t.Blob[:131072]...)
	}
	{ // Static Field #1 'Proof'
		dst = append(dst, t.Proof[:48]...)
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BlobAndProof from SSZ-encoded bytes.
func (t *BlobAndProof) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 131120 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 131120)
	}
	if buflen > 131120 {
		return sszutils.ErrTrailingDataFn(buflen - 131120)
	}
	{ // Field #0 'Blob' (static)
		buf := buf[0:131072]
		copy(t.Blob[:], buf)
	}
	{ // Field #1 'Proof' (static)
		buf := buf[131072:131120]
		copy(t.Proof[:], buf)
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BlobAndProof.
func (t *BlobAndProof) SizeSSZ() (size int) {
	return 131120
}

// HashTreeRoot computes the SSZ hash tree root of the *BlobAndProof.
func (t *BlobAndProof) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BlobAndProof using the given hash walker.
func (t *BlobAndProof) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlobAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Blob'
		hh.PutBytes(t.Blob[:131072])
	}
	{ // Field #1 'Proof'
		hh.PutBytes(t.Proof[:48])
	}
	hh.Merkleize(idx)
	return nil
}
