// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1f925094502a64e49c39b5d72059eb6eb1dd489ee2e2fe34a9d876be3e5a5189
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package cancun

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetBlobsResponse to SSZ-encoded bytes.
func (t *GetBlobsResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetBlobsResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetBlobsResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetBlobsResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobsAndProofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobsAndProofs'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobsAndProofs
		vlen := len(t)
		if vlen > 128 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetBlobsResponse from SSZ-encoded bytes.
func (t *GetBlobsResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobsAndProofs' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobsAndProofs:o")
	}
	{ // Field #0 'BlobsAndProofs' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobsAndProofs
		itemCount := len(buf) / 131120
		if len(buf)%131120 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131120), "BlobsAndProofs")
		}
		if itemCount > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 128), "BlobsAndProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(BlobAndProof)
			}
			buf := buf[131120*idx1 : 131120*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
		}
		t.BlobsAndProofs = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetBlobsResponse.
func (t *GetBlobsResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	// Field #0 'BlobsAndProofs' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobsAndProofs'
		size += len(t.BlobsAndProofs) * 131120
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetBlobsResponse.
func (t *GetBlobsResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetBlobsResponse using the given hash walker.
func (t *GetBlobsResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := uint64(len(t))
		if vlen > 128 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 128), "BlobsAndProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BlobsAndProofs[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(128, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
