// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 7c45f65631b0e5fe8f398a682e9b890df722a7fad4e244abf4b7c258827d223c
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package cancun

import (
	"encoding/binary"

	"github.com/holiman/uint256"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *GetPayloadResponse to SSZ-encoded bytes.
func (t *GetPayloadResponse) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *GetPayloadResponse to SSZ-encoded bytes, appending to the provided buffer.
func (t *GetPayloadResponse) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *GetPayloadResponse from SSZ-encoded bytes.
func (t *GetPayloadResponse) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 41 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 41)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 41 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 41), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if err = t.BlobsBundle.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *GetPayloadResponse.
func (t *GetPayloadResponse) SizeSSZ() (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	size += 41
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #2 'BlobsBundle'
		size += t.BlobsBundle.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *GetPayloadResponse.
func (t *GetPayloadResponse) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *GetPayloadResponse using the given hash walker.
func (t *GetPayloadResponse) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "BlobsBundle")
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	hh.Merkleize(idx)
	return nil
}
