// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 4e2f6fee427ba6263a7471379f8ad9655fa62c8b10c48f371d3e6a8cbabe4152
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package cancun

import (
	"encoding/binary"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[NewPayloadRequest](`ssz-static:"false"`)

// MarshalSSZ marshals the *NewPayloadRequest to SSZ-encoded bytes.
func (t *NewPayloadRequest) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *NewPayloadRequest to SSZ-encoded bytes, appending to the provided buffer.
func (t *NewPayloadRequest) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'ExpectedBlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Dynamic Field #1 'ExpectedBlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExpectedBlobVersionedHashes
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "ExpectedBlobVersionedHashes")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *NewPayloadRequest from SSZ-encoded bytes.
func (t *NewPayloadRequest) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 40 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 40)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 40 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 40), "ExecutionPayload:o")
	}
	// Field #1 'ExpectedBlobVersionedHashes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExpectedBlobVersionedHashes:o")
	}
	{ // Field #2 'ParentBeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if err = t.ExecutionPayload.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes' (dynamic)
		buf := buf[offset1:]
		val1 := t.ExpectedBlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "ExpectedBlobVersionedHashes")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "ExpectedBlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.ExpectedBlobVersionedHashes = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *NewPayloadRequest.
func (t *NewPayloadRequest) SizeSSZ() (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'ExpectedBlobVersionedHashes' offset (4 bytes)
	// Field #2 'ParentBeaconBlockRoot' static (32 bytes)
	size += 40
	{ // Dynamic field #0 'ExecutionPayload'
		size += t.ExecutionPayload.SizeSSZ()
	}
	{ // Dynamic field #1 'ExpectedBlobVersionedHashes'
		size += len(t.ExpectedBlobVersionedHashes) * 32
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *NewPayloadRequest.
func (t *NewPayloadRequest) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *NewPayloadRequest using the given hash walker.
func (t *NewPayloadRequest) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ExecutionPayload")
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes'
		t := t.ExpectedBlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "ExpectedBlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	{ // Field #2 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}
