// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 645bfbc6d9c46e093f732c4bbd646abbe2a44e567d8f7783b5ca08215ca0cdf3
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/osaka"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*cancun.BlobAndProof](`ssz-static:"true"`)
var _ = sszutils.Annotate[*osaka.BlobAndProof](`ssz-static:"false"`)

func (t *BlobAndProof) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *cancun.BlobAndProof:
		return t.marshalSSZView_BlobAndProof
	case *osaka.BlobAndProof:
		return t.marshalSSZView_BlobAndProof_0
	}
	return nil
}
func (t *BlobAndProof) marshalSSZView_BlobAndProof(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlobAndProof)
	}
	{ // Static Field #0 'Blob'
		dst = append(dst, t.Blob[:131072]...)
	}
	{ // Static Field #1 'Proof'
		dst = append(dst, t.Proof[:48]...)
	}
	return dst, nil
}

func (t *BlobAndProof) marshalSSZView_BlobAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "CELLS_PER_EXT_BLOB", 128)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(BlobAndProof)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Blob'
		dst = append(dst, t.Blob[:131072]...)
	}
	// Offset Field #1 'Proofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+131072:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Proofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *BlobAndProof) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *cancun.BlobAndProof:
		return t.unmarshalSSZView_BlobAndProof
	case *osaka.BlobAndProof:
		return t.unmarshalSSZView_BlobAndProof_0
	}
	return nil
}
func (t *BlobAndProof) unmarshalSSZView_BlobAndProof(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 131120 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 131120)
	}
	if buflen > 131120 {
		return sszutils.ErrTrailingDataFn(buflen - 131120)
	}
	{ // Field #0 'Blob' (static)
		buf := buf[0:131072]
		copy(t.Blob[:], buf)
	}
	{ // Field #1 'Proof' (static)
		buf := buf[131072:131120]
		copy(t.Proof[:], buf)
	}
	return nil
}

func (t *BlobAndProof) unmarshalSSZView_BlobAndProof_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "CELLS_PER_EXT_BLOB", 128)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 131076 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 131076)
	}
	{ // Field #0 'Blob' (static)
		buf := buf[0:131072]
		copy(t.Blob[:], buf)
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[131072:131076]))
	if offset1 != 131076 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 131076), "Proofs:o")
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:]
		val1 := t.Proofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Proofs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Proofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.Proofs = val1
	}
	return nil
}

func (t *BlobAndProof) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *cancun.BlobAndProof:
		return t.sizeSSZView_BlobAndProof
	case *osaka.BlobAndProof:
		return t.sizeSSZView_BlobAndProof_0
	}
	return nil
}
func (t *BlobAndProof) sizeSSZView_BlobAndProof(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlobAndProof)
	}
	// Field #0 'Blob' static (131072 bytes)
	// Field #1 'Proof' static (48 bytes)
	size += 131120
	return size
}

func (t *BlobAndProof) sizeSSZView_BlobAndProof_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlobAndProof)
	}
	// Field #0 'Blob' static (131072 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	size += 131076
	{ // Dynamic field #1 'Proofs'
		size += len(t.Proofs) * 48
	}
	return size
}

func (t *BlobAndProof) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *cancun.BlobAndProof:
		return t.hashTreeRootView_BlobAndProof
	case *osaka.BlobAndProof:
		return t.hashTreeRootView_BlobAndProof_0
	}
	return nil
}
func (t *BlobAndProof) hashTreeRootView_BlobAndProof(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlobAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Blob'
		hh.PutBytes(t.Blob[:131072])
	}
	{ // Field #1 'Proof'
		hh.PutBytes(t.Proof[:48])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlobAndProof) hashTreeRootView_BlobAndProof_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "CELLS_PER_EXT_BLOB", 128)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BlobAndProof)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Blob'
		hh.PutBytes(t.Blob[:131072])
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
