// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 61eddce98328ec68359cc16c0458ebe1bfcbf7f8b0d42901ac7514e0d0afaa42
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/osaka"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *BlobsBundle) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *cancun.BlobsBundle:
		return t.marshalSSZView_BlobsBundle
	case *osaka.BlobsBundle:
		return t.marshalSSZView_BlobsBundle_0
	}
	return nil
}
func (t *BlobsBundle) marshalSSZView_BlobsBundle(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlobsBundle)
	}
	dstlen := len(dst)
	// Offset Field #0 'Commitments'
	// Offset Field #1 'Proofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Commitments'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Commitments
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Commitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Proofs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #2 'Blobs'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Blobs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Blobs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:131072]...)
		}
	}
	return dst, nil
}

func (t *BlobsBundle) marshalSSZView_BlobsBundle_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK*CELLS_PER_EXT_BLOB", 524288)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlobsBundle)
	}
	dstlen := len(dst)
	// Offset Field #0 'Commitments'
	// Offset Field #1 'Proofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Commitments'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Commitments
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Commitments")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #1 'Proofs'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Proofs
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "Proofs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:48]...)
		}
	}
	{ // Dynamic Field #2 'Blobs'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Blobs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Blobs")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:131072]...)
		}
	}
	return dst, nil
}

func (t *BlobsBundle) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *cancun.BlobsBundle:
		return t.unmarshalSSZView_BlobsBundle
	case *osaka.BlobsBundle:
		return t.unmarshalSSZView_BlobsBundle_0
	}
	return nil
}
func (t *BlobsBundle) unmarshalSSZView_BlobsBundle(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'Commitments' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Commitments:o")
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Proofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Commitments' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Commitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Commitments")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Commitments")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.Commitments = val1
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.Proofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Proofs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Proofs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.Proofs = val2
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val3 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Blobs")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			buf := buf[131072*idx1 : 131072*(idx1+1)]
			copy(val3[idx1][:], buf)
		}
		t.Blobs = val3
	}
	return nil
}

func (t *BlobsBundle) unmarshalSSZView_BlobsBundle_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK*CELLS_PER_EXT_BLOB", 524288)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'Commitments' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Commitments:o")
	}
	// Field #1 'Proofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Proofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Commitments' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Commitments
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Commitments")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Commitments")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.Commitments = val1
	}
	{ // Field #1 'Proofs' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.Proofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "Proofs")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "Proofs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			buf := buf[48*idx1 : 48*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.Proofs = val2
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val3 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Blobs")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			buf := buf[131072*idx1 : 131072*(idx1+1)]
			copy(val3[idx1][:], buf)
		}
		t.Blobs = val3
	}
	return nil
}

func (t *BlobsBundle) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *cancun.BlobsBundle:
		return t.sizeSSZView_BlobsBundle
	case *osaka.BlobsBundle:
		return t.sizeSSZView_BlobsBundle_0
	}
	return nil
}
func (t *BlobsBundle) sizeSSZView_BlobsBundle(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlobsBundle)
	}
	// Field #0 'Commitments' offset (4 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Commitments'
		size += len(t.Commitments) * 48
	}
	{ // Dynamic field #1 'Proofs'
		size += len(t.Proofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

func (t *BlobsBundle) sizeSSZView_BlobsBundle_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlobsBundle)
	}
	// Field #0 'Commitments' offset (4 bytes)
	// Field #1 'Proofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Commitments'
		size += len(t.Commitments) * 48
	}
	{ // Dynamic field #1 'Proofs'
		size += len(t.Proofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

func (t *BlobsBundle) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *cancun.BlobsBundle:
		return t.hashTreeRootView_BlobsBundle
	case *osaka.BlobsBundle:
		return t.hashTreeRootView_BlobsBundle_0
	}
	return nil
}
func (t *BlobsBundle) hashTreeRootView_BlobsBundle(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BlobsBundle)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Commitments'
		t := t.Commitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Commitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlobsBundle) hashTreeRootView_BlobsBundle_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK*CELLS_PER_EXT_BLOB", 524288)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BlobsBundle)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Commitments'
		t := t.Commitments
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Commitments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #1 'Proofs'
		t := t.Proofs
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Proofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
