// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 185ac29d6d332052ef439a760b304c3882cb902cbebadcc7be00dd35a2c2b4a3
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/amsterdam"
	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*shanghai.ExecutionPayloadBody](`ssz-static:"false"`)
var _ = sszutils.Annotate[*amsterdam.ExecutionPayloadBody](`ssz-static:"false"`)

func (t *ExecutionPayloadBody) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *shanghai.ExecutionPayloadBody:
		return t.marshalSSZView_ExecutionPayloadBody
	case *amsterdam.ExecutionPayloadBody:
		return t.marshalSSZView_ExecutionPayloadBody_0
	}
	return nil
}
func (t *ExecutionPayloadBody) marshalSSZView_ExecutionPayloadBody(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	dstlen := len(dst)
	// Offset Field #0 'Transactions'
	// Offset Field #1 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #1 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr2) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr2)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadBody) marshalSSZView_ExecutionPayloadBody_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	dstlen := len(dst)
	// Offset Field #0 'Transactions'
	// Offset Field #1 'Withdrawals'
	// Offset Field #2 'BlockAccessList'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Transactions'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Transactions
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Transactions")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr1)), "Transactions[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	{ // Dynamic Field #1 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr2) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr2)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #2 'BlockAccessList'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.BlockAccessList
		if t != nil {
			dst = binary.LittleEndian.AppendUint32(dst, 4)
			dst = append(dst, (*t)[:]...)
		}
	}
	return dst, nil
}

func (t *ExecutionPayloadBody) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *shanghai.ExecutionPayloadBody:
		return t.unmarshalSSZView_ExecutionPayloadBody
	case *amsterdam.ExecutionPayloadBody:
		return t.unmarshalSSZView_ExecutionPayloadBody_0
	}
	return nil
}
func (t *ExecutionPayloadBody) unmarshalSSZView_ExecutionPayloadBody(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	// Field #0 'Transactions' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "Transactions:o")
	}
	// Field #1 'Withdrawals' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Withdrawals:o")
	}
	{ // Field #0 'Transactions' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Transactions")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if len(buf) > int(expr1) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr1)), "Transactions[%d]", idx1)
			}
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	{ // Field #1 'Withdrawals' (dynamic)
		buf := buf[offset1:]
		val3 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr2) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr2)), "Withdrawals")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val3
	}
	return nil
}

func (t *ExecutionPayloadBody) unmarshalSSZView_ExecutionPayloadBody_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'Transactions' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Transactions:o")
	}
	// Field #1 'Withdrawals' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Withdrawals:o")
	}
	// Field #2 'BlockAccessList' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "BlockAccessList:o")
	}
	{ // Field #0 'Transactions' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "Transactions")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Transactions")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if len(buf) > int(expr1) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr1)), "Transactions[%d]", idx1)
			}
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	{ // Field #1 'Withdrawals' (dynamic)
		buf := buf[offset1:offset2]
		val3 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr2) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr2)), "Withdrawals")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val3
	}
	{ // Field #2 'BlockAccessList' (dynamic)
		buf := buf[offset2:]
		val4 := t.BlockAccessList
		if len(buf) == 0 {
			val4 = nil
		} else {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlockAccessList")
			}
			firstOffset := binary.LittleEndian.Uint32(buf[:4])
			if firstOffset != 4 {
				return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(firstOffset, uint32(4)), "BlockAccessList")
			}
			buf := buf[4:]
			var val5 amsterdam.BlockAccessList
			val5 = sszutils.ExpandSlice(val5, len(buf))
			copy(val5[:], buf)
			val4 = &val5
		}
		t.BlockAccessList = val4
	}
	return nil
}

func (t *ExecutionPayloadBody) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *shanghai.ExecutionPayloadBody:
		return t.sizeSSZView_ExecutionPayloadBody
	case *amsterdam.ExecutionPayloadBody:
		return t.sizeSSZView_ExecutionPayloadBody_0
	}
	return nil
}
func (t *ExecutionPayloadBody) sizeSSZView_ExecutionPayloadBody(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	// Field #0 'Transactions' offset (4 bytes)
	// Field #1 'Withdrawals' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #1 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *ExecutionPayloadBody) sizeSSZView_ExecutionPayloadBody_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	// Field #0 'Transactions' offset (4 bytes)
	// Field #1 'Withdrawals' offset (4 bytes)
	// Field #2 'BlockAccessList' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Transactions'
		t := t.Transactions
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	{ // Dynamic field #1 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	{ // Dynamic field #2 'BlockAccessList'
		if t.BlockAccessList != nil {
			size += 4 // optional-list offset header
			size += len((*t.BlockAccessList))
		}
	}
	return size
}

func (t *ExecutionPayloadBody) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *shanghai.ExecutionPayloadBody:
		return t.hashTreeRootView_ExecutionPayloadBody
	case *amsterdam.ExecutionPayloadBody:
		return t.hashTreeRootView_ExecutionPayloadBody_0
	}
	return nil
}
func (t *ExecutionPayloadBody) hashTreeRootView_ExecutionPayloadBody(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr1 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr1), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #1 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionPayloadBody) hashTreeRootView_ExecutionPayloadBody_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionPayloadBody)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Transactions'
		t := t.Transactions
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Transactions")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr1 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr1), "Transactions[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #1 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 32))
	}
	{ // Field #2 'BlockAccessList'
		t := t.BlockAccessList
		{
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			vlen := uint64(0)
			if t != nil {
				idx := hh.StartTree(sszutils.TreeTypeBinary)
				hh.AppendBytes32((*t)[:])
				hh.Merkleize(idx)
				vlen = 1
			}
			hh.FillUpTo32()
			hh.MerkleizeWithMixin(idx, vlen, 1)
		}
	}
	hh.Merkleize(idx)
	return nil
}
