// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 1cec6bcf10a17b857c982079d8349934f91df043c57a78bd304e4031269a0081
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/amsterdam"
	"github.com/ethpandaops/go-eth-engine-client/spec/bogota"
	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/paris"
	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*paris.ForkchoiceUpdatedRequest](`ssz-static:"false"`)
var _ = sszutils.Annotate[*shanghai.ForkchoiceUpdatedRequest](`ssz-static:"false"`)
var _ = sszutils.Annotate[*cancun.ForkchoiceUpdatedRequest](`ssz-static:"false"`)
var _ = sszutils.Annotate[*amsterdam.ForkchoiceUpdatedRequest](`ssz-static:"false"`)
var _ = sszutils.Annotate[*bogota.ForkchoiceUpdatedRequest](`ssz-static:"false"`)

func (t *ForkchoiceUpdatedRequest) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *paris.ForkchoiceUpdatedRequest:
		return t.marshalSSZView_ForkchoiceUpdatedRequest
	case *shanghai.ForkchoiceUpdatedRequest:
		return t.marshalSSZView_ForkchoiceUpdatedRequest_0
	case *cancun.ForkchoiceUpdatedRequest:
		return t.marshalSSZView_ForkchoiceUpdatedRequest_1
	case *amsterdam.ForkchoiceUpdatedRequest:
		return t.marshalSSZView_ForkchoiceUpdatedRequest_2
	case *bogota.ForkchoiceUpdatedRequest:
		return t.marshalSSZView_ForkchoiceUpdatedRequest_3
	}
	return nil
}
func (t *ForkchoiceUpdatedRequest) marshalSSZView_ForkchoiceUpdatedRequest(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if viewFn := t.MarshalSSZDynView((*paris.PayloadAttributes)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *ForkchoiceUpdatedRequest) marshalSSZView_ForkchoiceUpdatedRequest_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if viewFn := t.MarshalSSZDynView((*shanghai.PayloadAttributes)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *ForkchoiceUpdatedRequest) marshalSSZView_ForkchoiceUpdatedRequest_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if viewFn := t.MarshalSSZDynView((*cancun.PayloadAttributes)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *ForkchoiceUpdatedRequest) marshalSSZView_ForkchoiceUpdatedRequest_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if viewFn := t.MarshalSSZDynView((*amsterdam.PayloadAttributes)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *ForkchoiceUpdatedRequest) marshalSSZView_ForkchoiceUpdatedRequest_3(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	dstlen := len(dst)
	{ // Static Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Offset Field #1 'PayloadAttributes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #1 'PayloadAttributes'
		binary.LittleEndian.PutUint32(dst[dstlen+96:], uint32(len(dst)-dstlen))
		t := t.PayloadAttributes
		if viewFn := t.MarshalSSZDynView((*bogota.PayloadAttributes)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *ForkchoiceUpdatedRequest) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *paris.ForkchoiceUpdatedRequest:
		return t.unmarshalSSZView_ForkchoiceUpdatedRequest
	case *shanghai.ForkchoiceUpdatedRequest:
		return t.unmarshalSSZView_ForkchoiceUpdatedRequest_0
	case *cancun.ForkchoiceUpdatedRequest:
		return t.unmarshalSSZView_ForkchoiceUpdatedRequest_1
	case *amsterdam.ForkchoiceUpdatedRequest:
		return t.unmarshalSSZView_ForkchoiceUpdatedRequest_2
	case *bogota.ForkchoiceUpdatedRequest:
		return t.unmarshalSSZView_ForkchoiceUpdatedRequest_3
	}
	return nil
}
func (t *ForkchoiceUpdatedRequest) unmarshalSSZView_ForkchoiceUpdatedRequest(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(paris.ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if viewFn := val1.UnmarshalSSZDynView((*paris.PayloadAttributes)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
		t.PayloadAttributes = val1
	}
	return nil
}

func (t *ForkchoiceUpdatedRequest) unmarshalSSZView_ForkchoiceUpdatedRequest_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(paris.ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if viewFn := val1.UnmarshalSSZDynView((*shanghai.PayloadAttributes)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
		t.PayloadAttributes = val1
	}
	return nil
}

func (t *ForkchoiceUpdatedRequest) unmarshalSSZView_ForkchoiceUpdatedRequest_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(paris.ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if viewFn := val1.UnmarshalSSZDynView((*cancun.PayloadAttributes)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
		t.PayloadAttributes = val1
	}
	return nil
}

func (t *ForkchoiceUpdatedRequest) unmarshalSSZView_ForkchoiceUpdatedRequest_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(paris.ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if viewFn := val1.UnmarshalSSZDynView((*amsterdam.PayloadAttributes)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
		t.PayloadAttributes = val1
	}
	return nil
}

func (t *ForkchoiceUpdatedRequest) unmarshalSSZView_ForkchoiceUpdatedRequest_3(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	{ // Field #0 'ForkchoiceState' (static)
		buf := buf[0:96]
		if t.ForkchoiceState == nil {
			t.ForkchoiceState = new(paris.ForkchoiceState)
		}
		if err = t.ForkchoiceState.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	// Field #1 'PayloadAttributes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[96:100]))
	if offset1 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset1, 100), "PayloadAttributes:o")
	}
	{ // Field #1 'PayloadAttributes' (dynamic)
		buf := buf[offset1:]
		val1 := t.PayloadAttributes
		if viewFn := val1.UnmarshalSSZDynView((*bogota.PayloadAttributes)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
		t.PayloadAttributes = val1
	}
	return nil
}

func (t *ForkchoiceUpdatedRequest) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *paris.ForkchoiceUpdatedRequest:
		return t.sizeSSZView_ForkchoiceUpdatedRequest
	case *shanghai.ForkchoiceUpdatedRequest:
		return t.sizeSSZView_ForkchoiceUpdatedRequest_0
	case *cancun.ForkchoiceUpdatedRequest:
		return t.sizeSSZView_ForkchoiceUpdatedRequest_1
	case *amsterdam.ForkchoiceUpdatedRequest:
		return t.sizeSSZView_ForkchoiceUpdatedRequest_2
	case *bogota.ForkchoiceUpdatedRequest:
		return t.sizeSSZView_ForkchoiceUpdatedRequest_3
	}
	return nil
}
func (t *ForkchoiceUpdatedRequest) sizeSSZView_ForkchoiceUpdatedRequest(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if viewFn := t.PayloadAttributes.SizeSSZDynView((*paris.PayloadAttributes)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *ForkchoiceUpdatedRequest) sizeSSZView_ForkchoiceUpdatedRequest_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if viewFn := t.PayloadAttributes.SizeSSZDynView((*shanghai.PayloadAttributes)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *ForkchoiceUpdatedRequest) sizeSSZView_ForkchoiceUpdatedRequest_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if viewFn := t.PayloadAttributes.SizeSSZDynView((*cancun.PayloadAttributes)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *ForkchoiceUpdatedRequest) sizeSSZView_ForkchoiceUpdatedRequest_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if viewFn := t.PayloadAttributes.SizeSSZDynView((*amsterdam.PayloadAttributes)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *ForkchoiceUpdatedRequest) sizeSSZView_ForkchoiceUpdatedRequest_3(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	// Field #0 'ForkchoiceState' static (96 bytes)
	// Field #1 'PayloadAttributes' offset (4 bytes)
	size += 100
	{ // Dynamic field #1 'PayloadAttributes'
		if viewFn := t.PayloadAttributes.SizeSSZDynView((*bogota.PayloadAttributes)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *ForkchoiceUpdatedRequest) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *paris.ForkchoiceUpdatedRequest:
		return t.hashTreeRootView_ForkchoiceUpdatedRequest
	case *shanghai.ForkchoiceUpdatedRequest:
		return t.hashTreeRootView_ForkchoiceUpdatedRequest_0
	case *cancun.ForkchoiceUpdatedRequest:
		return t.hashTreeRootView_ForkchoiceUpdatedRequest_1
	case *amsterdam.ForkchoiceUpdatedRequest:
		return t.hashTreeRootView_ForkchoiceUpdatedRequest_2
	case *bogota.ForkchoiceUpdatedRequest:
		return t.hashTreeRootView_ForkchoiceUpdatedRequest_3
	}
	return nil
}
func (t *ForkchoiceUpdatedRequest) hashTreeRootView_ForkchoiceUpdatedRequest(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		if viewFn := t.HashTreeRootWithDynView((*paris.PayloadAttributes)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ForkchoiceUpdatedRequest) hashTreeRootView_ForkchoiceUpdatedRequest_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		if viewFn := t.HashTreeRootWithDynView((*shanghai.PayloadAttributes)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ForkchoiceUpdatedRequest) hashTreeRootView_ForkchoiceUpdatedRequest_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		if viewFn := t.HashTreeRootWithDynView((*cancun.PayloadAttributes)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ForkchoiceUpdatedRequest) hashTreeRootView_ForkchoiceUpdatedRequest_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		if viewFn := t.HashTreeRootWithDynView((*amsterdam.PayloadAttributes)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ForkchoiceUpdatedRequest) hashTreeRootView_ForkchoiceUpdatedRequest_3(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ForkchoiceUpdatedRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ForkchoiceState'
		t := t.ForkchoiceState
		if t == nil {
			t = new(paris.ForkchoiceState)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ForkchoiceState")
		}
	}
	{ // Field #1 'PayloadAttributes'
		t := t.PayloadAttributes
		if viewFn := t.HashTreeRootWithDynView((*bogota.PayloadAttributes)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}
