// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 99b963edb5738c99bbb7a30b42d21f1e70032e1b0e402e09b602fa7e21478be3
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/osaka"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*cancun.GetBlobsRequest](`ssz-static:"false"`)
var _ = sszutils.Annotate[*osaka.GetBlobsRequest](`ssz-static:"false"`)

func (t *GetBlobsRequest) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *cancun.GetBlobsRequest:
		return t.marshalSSZView_GetBlobsRequest
	case *osaka.GetBlobsRequest:
		return t.marshalSSZView_GetBlobsRequest_0
	}
	return nil
}
func (t *GetBlobsRequest) marshalSSZView_GetBlobsRequest(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetBlobsRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobVersionedHashes
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobVersionedHashes")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *GetBlobsRequest) marshalSSZView_GetBlobsRequest_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetBlobsRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobVersionedHashes
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobVersionedHashes")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *GetBlobsRequest) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *cancun.GetBlobsRequest:
		return t.unmarshalSSZView_GetBlobsRequest
	case *osaka.GetBlobsRequest:
		return t.unmarshalSSZView_GetBlobsRequest_0
	}
	return nil
}
func (t *GetBlobsRequest) unmarshalSSZView_GetBlobsRequest(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobVersionedHashes' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobVersionedHashes:o")
	}
	{ // Field #0 'BlobVersionedHashes' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "BlobVersionedHashes")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.BlobVersionedHashes = val1
	}
	return nil
}

func (t *GetBlobsRequest) unmarshalSSZView_GetBlobsRequest_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobVersionedHashes' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobVersionedHashes:o")
	}
	{ // Field #0 'BlobVersionedHashes' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "BlobVersionedHashes")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.BlobVersionedHashes = val1
	}
	return nil
}

func (t *GetBlobsRequest) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *cancun.GetBlobsRequest:
		return t.sizeSSZView_GetBlobsRequest
	case *osaka.GetBlobsRequest:
		return t.sizeSSZView_GetBlobsRequest_0
	}
	return nil
}
func (t *GetBlobsRequest) sizeSSZView_GetBlobsRequest(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetBlobsRequest)
	}
	// Field #0 'BlobVersionedHashes' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobVersionedHashes'
		size += len(t.BlobVersionedHashes) * 32
	}
	return size
}

func (t *GetBlobsRequest) sizeSSZView_GetBlobsRequest_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetBlobsRequest)
	}
	// Field #0 'BlobVersionedHashes' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobVersionedHashes'
		size += len(t.BlobVersionedHashes) * 32
	}
	return size
}

func (t *GetBlobsRequest) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *cancun.GetBlobsRequest:
		return t.hashTreeRootView_GetBlobsRequest
	case *osaka.GetBlobsRequest:
		return t.hashTreeRootView_GetBlobsRequest_0
	}
	return nil
}
func (t *GetBlobsRequest) hashTreeRootView_GetBlobsRequest(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetBlobsRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobVersionedHashes'
		t := t.BlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetBlobsRequest) hashTreeRootView_GetBlobsRequest_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetBlobsRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobVersionedHashes'
		t := t.BlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
