// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: f14fa24459a80679116592485ddd971e388bf9b8d11ecdd586bd49fa9d144f66
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/osaka"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *GetBlobsResponse) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *cancun.GetBlobsResponse:
		return t.marshalSSZView_GetBlobsResponse
	case *osaka.GetBlobsResponse:
		return t.marshalSSZView_GetBlobsResponse_0
	}
	return nil
}
func (t *GetBlobsResponse) marshalSSZView_GetBlobsResponse(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetBlobsResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobsAndProofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobsAndProofs'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobsAndProofs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobsAndProofs")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if viewFn := t.MarshalSSZDynView((*cancun.BlobAndProof)(nil)); viewFn != nil {
				if dst, err = viewFn(ds, dst); err != nil {
					return nil, err
				}
			} else {
				return nil, sszutils.ErrNotImplemented
			}
		}
	}
	return dst, nil
}

func (t *GetBlobsResponse) marshalSSZView_GetBlobsResponse_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetBlobsResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'BlobsAndProofs'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'BlobsAndProofs'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.BlobsAndProofs
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "BlobsAndProofs")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if viewFn := t.MarshalSSZDynView((*osaka.BlobAndProof)(nil)); viewFn != nil {
				if dst, err = viewFn(ds, dst); err != nil {
					return nil, err
				}
			} else {
				return nil, sszutils.ErrNotImplemented
			}
		}
	}
	return dst, nil
}

func (t *GetBlobsResponse) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *cancun.GetBlobsResponse:
		return t.unmarshalSSZView_GetBlobsResponse
	case *osaka.GetBlobsResponse:
		return t.unmarshalSSZView_GetBlobsResponse_0
	}
	return nil
}
func (t *GetBlobsResponse) unmarshalSSZView_GetBlobsResponse(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobsAndProofs' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobsAndProofs:o")
	}
	{ // Field #0 'BlobsAndProofs' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobsAndProofs
		itemCount := len(buf) / 131120
		if len(buf)%131120 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131120), "BlobsAndProofs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobsAndProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(BlobAndProof)
			}
			buf := buf[131120*idx1 : 131120*(idx1+1)]
			if viewFn := val1[idx1].UnmarshalSSZDynView((*cancun.BlobAndProof)(nil)); viewFn != nil {
				if err = viewFn(ds, buf); err != nil {
					return err
				}
			} else {
				return sszutils.ErrNotImplemented
			}
		}
		t.BlobsAndProofs = val1
	}
	return nil
}

func (t *GetBlobsResponse) unmarshalSSZView_GetBlobsResponse_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'BlobsAndProofs' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "BlobsAndProofs:o")
	}
	{ // Field #0 'BlobsAndProofs' (dynamic)
		buf := buf[offset0:]
		val1 := t.BlobsAndProofs
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "BlobsAndProofs")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "BlobsAndProofs")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "BlobsAndProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "BlobsAndProofs[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			if val2 == nil {
				val2 = new(BlobAndProof)
			}
			if viewFn := val2.UnmarshalSSZDynView((*osaka.BlobAndProof)(nil)); viewFn != nil {
				if err = viewFn(ds, buf); err != nil {
					return err
				}
			} else {
				return sszutils.ErrNotImplemented
			}
			val1[idx1] = val2
		}
		t.BlobsAndProofs = val1
	}
	return nil
}

func (t *GetBlobsResponse) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *cancun.GetBlobsResponse:
		return t.sizeSSZView_GetBlobsResponse
	case *osaka.GetBlobsResponse:
		return t.sizeSSZView_GetBlobsResponse_0
	}
	return nil
}
func (t *GetBlobsResponse) sizeSSZView_GetBlobsResponse(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	// Field #0 'BlobsAndProofs' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobsAndProofs'
		size += len(t.BlobsAndProofs) * 131120
	}
	return size
}

func (t *GetBlobsResponse) sizeSSZView_GetBlobsResponse_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetBlobsResponse)
	}
	// Field #0 'BlobsAndProofs' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			if viewFn := t[i1].SizeSSZDynView((*osaka.BlobAndProof)(nil)); viewFn != nil {
				size += viewFn(ds)
			}
		}
	}
	return size
}

func (t *GetBlobsResponse) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *cancun.GetBlobsResponse:
		return t.hashTreeRootView_GetBlobsResponse
	case *osaka.GetBlobsResponse:
		return t.hashTreeRootView_GetBlobsResponse_0
	}
	return nil
}
func (t *GetBlobsResponse) hashTreeRootView_GetBlobsResponse(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetBlobsResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobsAndProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if viewFn := t.HashTreeRootWithDynView((*cancun.BlobAndProof)(nil)); viewFn != nil {
				if err := viewFn(ds, hh); err != nil {
					return err
				}
			} else {
				return sszutils.ErrNotImplemented
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetBlobsResponse) hashTreeRootView_GetBlobsResponse_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_HASHES_REQUEST", 128)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetBlobsResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'BlobsAndProofs'
		t := t.BlobsAndProofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "BlobsAndProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(BlobAndProof)
			}
			if viewFn := t.HashTreeRootWithDynView((*osaka.BlobAndProof)(nil)); viewFn != nil {
				if err := viewFn(ds, hh); err != nil {
					return err
				}
			} else {
				return sszutils.ErrNotImplemented
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
