// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 6f9ccc1a586684daef3099b74c2de2376589a37c21813fd2bc47051b1054e947
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/amsterdam"
	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/osaka"
	"github.com/ethpandaops/go-eth-engine-client/spec/prague"
	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	"github.com/holiman/uint256"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*shanghai.GetPayloadResponse](`ssz-static:"false"`)
var _ = sszutils.Annotate[*cancun.GetPayloadResponse](`ssz-static:"false"`)
var _ = sszutils.Annotate[*prague.GetPayloadResponse](`ssz-static:"false"`)
var _ = sszutils.Annotate[*osaka.GetPayloadResponse](`ssz-static:"false"`)
var _ = sszutils.Annotate[*amsterdam.GetPayloadResponse](`ssz-static:"false"`)

func (t *GetPayloadResponse) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *shanghai.GetPayloadResponse:
		return t.marshalSSZView_GetPayloadResponse
	case *cancun.GetPayloadResponse:
		return t.marshalSSZView_GetPayloadResponse_0
	case *prague.GetPayloadResponse:
		return t.marshalSSZView_GetPayloadResponse_1
	case *osaka.GetPayloadResponse:
		return t.marshalSSZView_GetPayloadResponse_2
	case *amsterdam.GetPayloadResponse:
		return t.marshalSSZView_GetPayloadResponse_3
	}
	return nil
}
func (t *GetPayloadResponse) marshalSSZView_GetPayloadResponse(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *GetPayloadResponse) marshalSSZView_GetPayloadResponse_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *GetPayloadResponse) marshalSSZView_GetPayloadResponse_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	// Offset Field #4 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #4 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+41:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *GetPayloadResponse) marshalSSZView_GetPayloadResponse_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	// Offset Field #4 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.MarshalSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #4 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+41:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *GetPayloadResponse) marshalSSZView_GetPayloadResponse_3(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
	}
	// Offset Field #2 'BlobsBundle'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #3 'ShouldOverrideBuilder'
		dst = sszutils.MarshalBool(dst, t.ShouldOverrideBuilder)
	}
	// Offset Field #4 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #2 'BlobsBundle'
		binary.LittleEndian.PutUint32(dst[dstlen+36:], uint32(len(dst)-dstlen))
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.MarshalSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #4 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+41:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr1) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *GetPayloadResponse) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *shanghai.GetPayloadResponse:
		return t.unmarshalSSZView_GetPayloadResponse
	case *cancun.GetPayloadResponse:
		return t.unmarshalSSZView_GetPayloadResponse_0
	case *prague.GetPayloadResponse:
		return t.unmarshalSSZView_GetPayloadResponse_1
	case *osaka.GetPayloadResponse:
		return t.unmarshalSSZView_GetPayloadResponse_2
	case *amsterdam.GetPayloadResponse:
		return t.unmarshalSSZView_GetPayloadResponse_3
	}
	return nil
}
func (t *GetPayloadResponse) unmarshalSSZView_GetPayloadResponse(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 36 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 36)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 36 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 36), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *GetPayloadResponse) unmarshalSSZView_GetPayloadResponse_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 41 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 41)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 41 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 41), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if viewFn := t.BlobsBundle.UnmarshalSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *GetPayloadResponse) unmarshalSSZView_GetPayloadResponse_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 45 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 45)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 45 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 45), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	// Field #4 'ExecutionRequests' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[41:45]))
	if offset4 < offset2 || offset4 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset2, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:offset4]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if viewFn := t.BlobsBundle.UnmarshalSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #4 'ExecutionRequests' (dynamic)
		buf := buf[offset4:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr1) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

func (t *GetPayloadResponse) unmarshalSSZView_GetPayloadResponse_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 45 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 45)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 45 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 45), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	// Field #4 'ExecutionRequests' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[41:45]))
	if offset4 < offset2 || offset4 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset2, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:offset4]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if viewFn := t.BlobsBundle.UnmarshalSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #4 'ExecutionRequests' (dynamic)
		buf := buf[offset4:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr1) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

func (t *GetPayloadResponse) unmarshalSSZView_GetPayloadResponse_3(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 45 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 45)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 45 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 45), "ExecutionPayload:o")
	}
	{ // Field #1 'BlockValue' (static)
		buf := buf[4:36]
		val1 := t.BlockValue
		if val1 == nil {
			val1 = new(uint256.Int)
		}
		sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
		t.BlockValue = val1
	}
	// Field #2 'BlobsBundle' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[36:40]))
	if offset2 < offset0 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset0, buflen), "BlobsBundle:o")
	}
	{ // Field #3 'ShouldOverrideBuilder' (static)
		buf := buf[40:41]
		if buf[0] != 1 && buf[0] != 0 {
			return sszutils.ErrInvalidBoolValueFn()
		}
		t.ShouldOverrideBuilder = buf[0] == 1
	}
	// Field #4 'ExecutionRequests' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[41:45]))
	if offset4 < offset2 || offset4 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset2, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset2]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #2 'BlobsBundle' (dynamic)
		buf := buf[offset2:offset4]
		if t.BlobsBundle == nil {
			t.BlobsBundle = new(BlobsBundle)
		}
		if viewFn := t.BlobsBundle.UnmarshalSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #4 'ExecutionRequests' (dynamic)
		buf := buf[offset4:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr1) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr1)), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

func (t *GetPayloadResponse) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *shanghai.GetPayloadResponse:
		return t.sizeSSZView_GetPayloadResponse
	case *cancun.GetPayloadResponse:
		return t.sizeSSZView_GetPayloadResponse_0
	case *prague.GetPayloadResponse:
		return t.sizeSSZView_GetPayloadResponse_1
	case *osaka.GetPayloadResponse:
		return t.sizeSSZView_GetPayloadResponse_2
	case *amsterdam.GetPayloadResponse:
		return t.sizeSSZView_GetPayloadResponse_3
	}
	return nil
}
func (t *GetPayloadResponse) sizeSSZView_GetPayloadResponse(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	size += 36
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *GetPayloadResponse) sizeSSZView_GetPayloadResponse_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	size += 41
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #2 'BlobsBundle'
		if viewFn := t.BlobsBundle.SizeSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *GetPayloadResponse) sizeSSZView_GetPayloadResponse_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	// Field #4 'ExecutionRequests' offset (4 bytes)
	size += 45
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #2 'BlobsBundle'
		if viewFn := t.BlobsBundle.SizeSSZDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *GetPayloadResponse) sizeSSZView_GetPayloadResponse_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	// Field #4 'ExecutionRequests' offset (4 bytes)
	size += 45
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #2 'BlobsBundle'
		if viewFn := t.BlobsBundle.SizeSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *GetPayloadResponse) sizeSSZView_GetPayloadResponse_3(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'BlockValue' static (32 bytes)
	// Field #2 'BlobsBundle' offset (4 bytes)
	// Field #3 'ShouldOverrideBuilder' static (1 bytes)
	// Field #4 'ExecutionRequests' offset (4 bytes)
	size += 45
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #2 'BlobsBundle'
		if viewFn := t.BlobsBundle.SizeSSZDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *GetPayloadResponse) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *shanghai.GetPayloadResponse:
		return t.hashTreeRootView_GetPayloadResponse
	case *cancun.GetPayloadResponse:
		return t.hashTreeRootView_GetPayloadResponse_0
	case *prague.GetPayloadResponse:
		return t.hashTreeRootView_GetPayloadResponse_1
	case *osaka.GetPayloadResponse:
		return t.hashTreeRootView_GetPayloadResponse_2
	case *amsterdam.GetPayloadResponse:
		return t.hashTreeRootView_GetPayloadResponse_3
	}
	return nil
}
func (t *GetPayloadResponse) hashTreeRootView_GetPayloadResponse(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetPayloadResponse) hashTreeRootView_GetPayloadResponse_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetPayloadResponse) hashTreeRootView_GetPayloadResponse_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.BlobsBundle)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	{ // Field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr1 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetPayloadResponse) hashTreeRootView_GetPayloadResponse_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.HashTreeRootWithDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	{ // Field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr1 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *GetPayloadResponse) hashTreeRootView_GetPayloadResponse_3(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(GetPayloadResponse)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'BlockValue'
		t := t.BlockValue
		if t == nil {
			t = new(uint256.Int)
		}
		if root, err := t.HashTreeRoot(); err != nil {
			return sszutils.ErrorWithPath(err, "BlockValue")
		} else {
			hh.AppendBytes32(root[:])
		}
	}
	{ // Field #2 'BlobsBundle'
		t := t.BlobsBundle
		if t == nil {
			t = new(BlobsBundle)
		}
		if viewFn := t.HashTreeRootWithDynView((*osaka.BlobsBundle)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #3 'ShouldOverrideBuilder'
		hh.PutBool(t.ShouldOverrideBuilder)
	}
	{ // Field #4 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr1 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
