// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: d01b493f4b6a39d7737ebc0117140486263a66397bbe0997f78ed73259f16cdd
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/amsterdam"
	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/paris"
	"github.com/ethpandaops/go-eth-engine-client/spec/prague"
	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *NewPayloadRequest) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *paris.NewPayloadRequest:
		return t.marshalSSZView_NewPayloadRequest
	case *shanghai.NewPayloadRequest:
		return t.marshalSSZView_NewPayloadRequest_0
	case *cancun.NewPayloadRequest:
		return t.marshalSSZView_NewPayloadRequest_1
	case *prague.NewPayloadRequest:
		return t.marshalSSZView_NewPayloadRequest_2
	case *amsterdam.NewPayloadRequest:
		return t.marshalSSZView_NewPayloadRequest_3
	}
	return nil
}
func (t *NewPayloadRequest) marshalSSZView_NewPayloadRequest(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*paris.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *NewPayloadRequest) marshalSSZView_NewPayloadRequest_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *NewPayloadRequest) marshalSSZView_NewPayloadRequest_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'ExpectedBlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'ExpectedBlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExpectedBlobVersionedHashes
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	return dst, nil
}

func (t *NewPayloadRequest) marshalSSZView_NewPayloadRequest_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'ExpectedBlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	// Offset Field #3 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'ExpectedBlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExpectedBlobVersionedHashes
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	{ // Dynamic Field #3 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+40:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *NewPayloadRequest) marshalSSZView_NewPayloadRequest_3(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	dstlen := len(dst)
	// Offset Field #0 'ExecutionPayload'
	// Offset Field #1 'ExpectedBlobVersionedHashes'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #2 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	// Offset Field #3 'ExecutionRequests'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #0 'ExecutionPayload'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.MarshalSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'ExpectedBlobVersionedHashes'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.ExpectedBlobVersionedHashes
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	{ // Dynamic Field #3 'ExecutionRequests'
		binary.LittleEndian.PutUint32(dst[dstlen+40:], uint32(len(dst)-dstlen))
		t := t.ExecutionRequests
		vlen := len(t)
		if vlen > int(expr1) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "ExecutionRequests")
		}
		dstlen := len(dst)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
			vlen := len(t[idx1])
			if vlen > int(expr2) {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "ExecutionRequests[%d]", idx1)
			}
			dst = append(dst, t[idx1][:]...)
		}
	}
	return dst, nil
}

func (t *NewPayloadRequest) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *paris.NewPayloadRequest:
		return t.unmarshalSSZView_NewPayloadRequest
	case *shanghai.NewPayloadRequest:
		return t.unmarshalSSZView_NewPayloadRequest_0
	case *cancun.NewPayloadRequest:
		return t.unmarshalSSZView_NewPayloadRequest_1
	case *prague.NewPayloadRequest:
		return t.unmarshalSSZView_NewPayloadRequest_2
	case *amsterdam.NewPayloadRequest:
		return t.unmarshalSSZView_NewPayloadRequest_3
	}
	return nil
}
func (t *NewPayloadRequest) unmarshalSSZView_NewPayloadRequest(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "ExecutionPayload:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*paris.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *NewPayloadRequest) unmarshalSSZView_NewPayloadRequest_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 4 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 4)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 4 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 4), "ExecutionPayload:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *NewPayloadRequest) unmarshalSSZView_NewPayloadRequest_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 40 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 40)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 40 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 40), "ExecutionPayload:o")
	}
	// Field #1 'ExpectedBlobVersionedHashes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExpectedBlobVersionedHashes:o")
	}
	{ // Field #2 'ParentBeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes' (dynamic)
		buf := buf[offset1:]
		val1 := t.ExpectedBlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "ExpectedBlobVersionedHashes")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.ExpectedBlobVersionedHashes = val1
	}
	return nil
}

func (t *NewPayloadRequest) unmarshalSSZView_NewPayloadRequest_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 44)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 44 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 44), "ExecutionPayload:o")
	}
	// Field #1 'ExpectedBlobVersionedHashes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExpectedBlobVersionedHashes:o")
	}
	{ // Field #2 'ParentBeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	// Field #3 'ExecutionRequests' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[40:44]))
	if offset3 < offset1 || offset3 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset1, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes' (dynamic)
		buf := buf[offset1:offset3]
		val1 := t.ExpectedBlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "ExpectedBlobVersionedHashes")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.ExpectedBlobVersionedHashes = val1
	}
	{ // Field #3 'ExecutionRequests' (dynamic)
		buf := buf[offset3:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

func (t *NewPayloadRequest) unmarshalSSZView_NewPayloadRequest_3(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 44 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 44)
	}
	// Field #0 'ExecutionPayload' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 44 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 44), "ExecutionPayload:o")
	}
	// Field #1 'ExpectedBlobVersionedHashes' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "ExpectedBlobVersionedHashes:o")
	}
	{ // Field #2 'ParentBeaconBlockRoot' (static)
		buf := buf[8:40]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	// Field #3 'ExecutionRequests' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[40:44]))
	if offset3 < offset1 || offset3 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset1, buflen), "ExecutionRequests:o")
	}
	{ // Field #0 'ExecutionPayload' (dynamic)
		buf := buf[offset0:offset1]
		if t.ExecutionPayload == nil {
			t.ExecutionPayload = new(ExecutionPayload)
		}
		if viewFn := t.ExecutionPayload.UnmarshalSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes' (dynamic)
		buf := buf[offset1:offset3]
		val1 := t.ExpectedBlobVersionedHashes
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "ExpectedBlobVersionedHashes")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "ExpectedBlobVersionedHashes")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.ExpectedBlobVersionedHashes = val1
	}
	{ // Field #3 'ExecutionRequests' (dynamic)
		buf := buf[offset3:]
		val2 := t.ExecutionRequests
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "ExecutionRequests")
			}
			startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
		}
		itemCount := startOffset / 4
		if startOffset%4 != 0 || len(buf) < startOffset {
			return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "ExecutionRequests")
		}
		if itemCount > int(expr1) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "ExecutionRequests")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "ExecutionRequests[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if len(buf) > int(expr2) {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "ExecutionRequests[%d]", idx1)
			}
			val3 = sszutils.ExpandSlice(val3, len(buf))
			copy(val3[:], buf)
			val2[idx1] = val3
		}
		t.ExecutionRequests = val2
	}
	return nil
}

func (t *NewPayloadRequest) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *paris.NewPayloadRequest:
		return t.sizeSSZView_NewPayloadRequest
	case *shanghai.NewPayloadRequest:
		return t.sizeSSZView_NewPayloadRequest_0
	case *cancun.NewPayloadRequest:
		return t.sizeSSZView_NewPayloadRequest_1
	case *prague.NewPayloadRequest:
		return t.sizeSSZView_NewPayloadRequest_2
	case *amsterdam.NewPayloadRequest:
		return t.sizeSSZView_NewPayloadRequest_3
	}
	return nil
}
func (t *NewPayloadRequest) sizeSSZView_NewPayloadRequest(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*paris.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *NewPayloadRequest) sizeSSZView_NewPayloadRequest_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	size += 4
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *NewPayloadRequest) sizeSSZView_NewPayloadRequest_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'ExpectedBlobVersionedHashes' offset (4 bytes)
	// Field #2 'ParentBeaconBlockRoot' static (32 bytes)
	size += 40
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'ExpectedBlobVersionedHashes'
		size += len(t.ExpectedBlobVersionedHashes) * 32
	}
	return size
}

func (t *NewPayloadRequest) sizeSSZView_NewPayloadRequest_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'ExpectedBlobVersionedHashes' offset (4 bytes)
	// Field #2 'ParentBeaconBlockRoot' static (32 bytes)
	// Field #3 'ExecutionRequests' offset (4 bytes)
	size += 44
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'ExpectedBlobVersionedHashes'
		size += len(t.ExpectedBlobVersionedHashes) * 32
	}
	{ // Dynamic field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *NewPayloadRequest) sizeSSZView_NewPayloadRequest_3(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	// Field #0 'ExecutionPayload' offset (4 bytes)
	// Field #1 'ExpectedBlobVersionedHashes' offset (4 bytes)
	// Field #2 'ParentBeaconBlockRoot' static (32 bytes)
	// Field #3 'ExecutionRequests' offset (4 bytes)
	size += 44
	{ // Dynamic field #0 'ExecutionPayload'
		if viewFn := t.ExecutionPayload.SizeSSZDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'ExpectedBlobVersionedHashes'
		size += len(t.ExpectedBlobVersionedHashes) * 32
	}
	{ // Dynamic field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := len(t)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t[i1])
		}
	}
	return size
}

func (t *NewPayloadRequest) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *paris.NewPayloadRequest:
		return t.hashTreeRootView_NewPayloadRequest
	case *shanghai.NewPayloadRequest:
		return t.hashTreeRootView_NewPayloadRequest_0
	case *cancun.NewPayloadRequest:
		return t.hashTreeRootView_NewPayloadRequest_1
	case *prague.NewPayloadRequest:
		return t.hashTreeRootView_NewPayloadRequest_2
	case *amsterdam.NewPayloadRequest:
		return t.hashTreeRootView_NewPayloadRequest_3
	}
	return nil
}
func (t *NewPayloadRequest) hashTreeRootView_NewPayloadRequest(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*paris.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *NewPayloadRequest) hashTreeRootView_NewPayloadRequest_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*shanghai.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *NewPayloadRequest) hashTreeRootView_NewPayloadRequest_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes'
		t := t.ExpectedBlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExpectedBlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *NewPayloadRequest) hashTreeRootView_NewPayloadRequest_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*cancun.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes'
		t := t.ExpectedBlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExpectedBlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	{ // Field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *NewPayloadRequest) hashTreeRootView_NewPayloadRequest_3(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXECUTION_REQUESTS", 256)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(NewPayloadRequest)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'ExecutionPayload'
		t := t.ExecutionPayload
		if t == nil {
			t = new(ExecutionPayload)
		}
		if viewFn := t.HashTreeRootWithDynView((*amsterdam.ExecutionPayload)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'ExpectedBlobVersionedHashes'
		t := t.ExpectedBlobVersionedHashes
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "ExpectedBlobVersionedHashes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	{ // Field #3 'ExecutionRequests'
		t := t.ExecutionRequests
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "ExecutionRequests")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			vlen := uint64(len(t[idx1]))
			if vlen > expr2 {
				return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "ExecutionRequests[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary)
			hh.AppendBytes32(t[idx1][:])
			hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
