// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: dce93b0105b42ca90f9b420112da68f7bfc74ace7975078016cb0f31df30b354
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth-engine-client/spec/amsterdam"
	"github.com/ethpandaops/go-eth-engine-client/spec/cancun"
	"github.com/ethpandaops/go-eth-engine-client/spec/paris"
	"github.com/ethpandaops/go-eth-engine-client/spec/shanghai"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *PayloadAttributes) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *paris.PayloadAttributes:
		return t.marshalSSZView_PayloadAttributes
	case *shanghai.PayloadAttributes:
		return t.marshalSSZView_PayloadAttributes_0
	case *cancun.PayloadAttributes:
		return t.marshalSSZView_PayloadAttributes_1
	case *amsterdam.PayloadAttributes:
		return t.marshalSSZView_PayloadAttributes_2
	}
	return nil
}
func (t *PayloadAttributes) marshalSSZView_PayloadAttributes(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(PayloadAttributes)
	}
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	return dst, nil
}

func (t *PayloadAttributes) marshalSSZView_PayloadAttributes_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	// Offset Field #3 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #3 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+60:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *PayloadAttributes) marshalSSZView_PayloadAttributes_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	// Offset Field #3 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #4 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Dynamic Field #3 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+60:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *PayloadAttributes) marshalSSZView_PayloadAttributes_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Timestamp'
		dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
	}
	{ // Static Field #1 'PrevRandao'
		dst = append(dst, t.PrevRandao[:32]...)
	}
	{ // Static Field #2 'SuggestedFeeRecipient'
		dst = append(dst, t.SuggestedFeeRecipient[:20]...)
	}
	// Offset Field #3 'Withdrawals'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #4 'ParentBeaconBlockRoot'
		dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
	}
	{ // Static Field #5 'SlotNumber'
		dst = binary.LittleEndian.AppendUint64(dst, t.SlotNumber)
	}
	{ // Static Field #6 'TargetGasLimit'
		dst = binary.LittleEndian.AppendUint64(dst, t.TargetGasLimit)
	}
	{ // Dynamic Field #3 'Withdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+60:], uint32(len(dst)-dstlen))
		t := t.Withdrawals
		vlen := len(t)
		if vlen > int(expr0) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *PayloadAttributes) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *paris.PayloadAttributes:
		return t.unmarshalSSZView_PayloadAttributes
	case *shanghai.PayloadAttributes:
		return t.unmarshalSSZView_PayloadAttributes_0
	case *cancun.PayloadAttributes:
		return t.unmarshalSSZView_PayloadAttributes_1
	case *amsterdam.PayloadAttributes:
		return t.unmarshalSSZView_PayloadAttributes_2
	}
	return nil
}
func (t *PayloadAttributes) unmarshalSSZView_PayloadAttributes(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 60 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 60)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	return nil
}

func (t *PayloadAttributes) unmarshalSSZView_PayloadAttributes_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 64 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 64)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	// Field #3 'Withdrawals' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[60:64]))
	if offset3 != 64 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 64), "Withdrawals:o")
	}
	{ // Field #3 'Withdrawals' (dynamic)
		buf := buf[offset3:]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	return nil
}

func (t *PayloadAttributes) unmarshalSSZView_PayloadAttributes_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 96 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 96)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	// Field #3 'Withdrawals' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[60:64]))
	if offset3 != 96 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 96), "Withdrawals:o")
	}
	{ // Field #4 'ParentBeaconBlockRoot' (static)
		buf := buf[64:96]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #3 'Withdrawals' (dynamic)
		buf := buf[offset3:]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	return nil
}

func (t *PayloadAttributes) unmarshalSSZView_PayloadAttributes_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 112 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 112)
	}
	{ // Field #0 'Timestamp' (static)
		buf := buf[0:8]
		t.Timestamp = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'PrevRandao' (static)
		buf := buf[8:40]
		copy(t.PrevRandao[:], buf)
	}
	{ // Field #2 'SuggestedFeeRecipient' (static)
		buf := buf[40:60]
		copy(t.SuggestedFeeRecipient[:], buf)
	}
	// Field #3 'Withdrawals' (offset)
	offset3 := int(binary.LittleEndian.Uint32(buf[60:64]))
	if offset3 != 112 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 112), "Withdrawals:o")
	}
	{ // Field #4 'ParentBeaconBlockRoot' (static)
		buf := buf[64:96]
		copy(t.ParentBeaconBlockRoot[:], buf)
	}
	{ // Field #5 'SlotNumber' (static)
		buf := buf[96:104]
		t.SlotNumber = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #6 'TargetGasLimit' (static)
		buf := buf[104:112]
		t.TargetGasLimit = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #3 'Withdrawals' (dynamic)
		buf := buf[offset3:]
		val1 := t.Withdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "Withdrawals")
		}
		if itemCount > int(expr0) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr0)), "Withdrawals")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(shanghai.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val1
	}
	return nil
}

func (t *PayloadAttributes) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *paris.PayloadAttributes:
		return t.sizeSSZView_PayloadAttributes
	case *shanghai.PayloadAttributes:
		return t.sizeSSZView_PayloadAttributes_0
	case *cancun.PayloadAttributes:
		return t.sizeSSZView_PayloadAttributes_1
	case *amsterdam.PayloadAttributes:
		return t.sizeSSZView_PayloadAttributes_2
	}
	return nil
}
func (t *PayloadAttributes) sizeSSZView_PayloadAttributes(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	size += 60
	return size
}

func (t *PayloadAttributes) sizeSSZView_PayloadAttributes_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	// Field #3 'Withdrawals' offset (4 bytes)
	size += 64
	{ // Dynamic field #3 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *PayloadAttributes) sizeSSZView_PayloadAttributes_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	// Field #3 'Withdrawals' offset (4 bytes)
	// Field #4 'ParentBeaconBlockRoot' static (32 bytes)
	size += 96
	{ // Dynamic field #3 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *PayloadAttributes) sizeSSZView_PayloadAttributes_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(PayloadAttributes)
	}
	// Field #0 'Timestamp' static (8 bytes)
	// Field #1 'PrevRandao' static (32 bytes)
	// Field #2 'SuggestedFeeRecipient' static (20 bytes)
	// Field #3 'Withdrawals' offset (4 bytes)
	// Field #4 'ParentBeaconBlockRoot' static (32 bytes)
	// Field #5 'SlotNumber' static (8 bytes)
	// Field #6 'TargetGasLimit' static (8 bytes)
	size += 112
	{ // Dynamic field #3 'Withdrawals'
		size += len(t.Withdrawals) * 44
	}
	return size
}

func (t *PayloadAttributes) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *paris.PayloadAttributes:
		return t.hashTreeRootView_PayloadAttributes
	case *shanghai.PayloadAttributes:
		return t.hashTreeRootView_PayloadAttributes_0
	case *cancun.PayloadAttributes:
		return t.hashTreeRootView_PayloadAttributes_1
	case *amsterdam.PayloadAttributes:
		return t.hashTreeRootView_PayloadAttributes_2
	}
	return nil
}
func (t *PayloadAttributes) hashTreeRootView_PayloadAttributes(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *PayloadAttributes) hashTreeRootView_PayloadAttributes_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	{ // Field #3 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *PayloadAttributes) hashTreeRootView_PayloadAttributes_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	{ // Field #3 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #4 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *PayloadAttributes) hashTreeRootView_PayloadAttributes_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(PayloadAttributes)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Timestamp'
		hh.PutUint64(t.Timestamp)
	}
	{ // Field #1 'PrevRandao'
		hh.PutBytes(t.PrevRandao[:32])
	}
	{ // Field #2 'SuggestedFeeRecipient'
		hh.PutBytes(t.SuggestedFeeRecipient[:20])
	}
	{ // Field #3 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(shanghai.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #4 'ParentBeaconBlockRoot'
		hh.PutBytes(t.ParentBeaconBlockRoot[:32])
	}
	{ // Field #5 'SlotNumber'
		hh.PutUint64(t.SlotNumber)
	}
	{ // Field #6 'TargetGasLimit'
		hh.PutUint64(t.TargetGasLimit)
	}
	hh.Merkleize(idx)
	return nil
}
